apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  selector:
    app: kafka-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32180
---
apiVersion: v1
kind: Service
metadata:
  name: localstack-service
spec:
  selector:
    app: localstack
  type: NodePort
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
      nodePort: 32566
