apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  selector:
    app: kafka-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32180
---
apiVersion: v1
kind: Service
metadata:
  name: localstack-service
spec:
  selector:
    app: localstack
  type: NodePort
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
      nodePort: 32566
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 32086
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  selector:
    app: telegraf
  type: NodePort
  ports:
    - name: udp1
      protocol: UDP
      port: 8125
      targetPort: 8125
      nodePort: 32125
    - name: udp2
      protocol: UDP
      port: 8092
      targetPort: 8092
      nodePort: 32092
    - name: telegraf
      protocol: TCP
      port: 8094
      targetPort: 8094
      nodePort: 32094
---
apiVersion: v1
kind: Service
metadata:
  name: s3manager-service
spec:
  selector:
    app: s3manager
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32280
